## Scipy

- Gaussian PDF - Probability distribution function

- Scipy is faster than regular tools

In [4]:
from scipy.stats import norm
import numpy as np

norm.pdf(0)

0.3989422804014327

In [2]:
# mean=5, stddev=10
norm.pdf(0, loc=5, scale=10)

0.035206532676429952

In [5]:
r = np.random.randn(10)
norm.pdf(r)

array([ 0.1104103 ,  0.07037728,  0.33686475,  0.11508102,  0.18770436,
        0.08088204,  0.12838062,  0.24900357,  0.39591574,  0.25127258])

## Log Pdf

Joint probability vs. log of joint probability of data samples (+ faster than &ast;)

Log of Gaussian PDF (much faster since no exponential!)

In [6]:
norm.logpdf(r)

array([-2.20355186, -2.65388479, -1.08807378, -2.1621189 , -1.67288709,
       -2.51476345, -2.05275582, -1.39028806, -0.92655388, -1.38121695])

CDF - Cumulative distribution function - integral of pdf from negative infinity to x

In [7]:
norm.cdf(r)

array([ 0.05448049,  0.96875231,  0.71958538,  0.0574185 ,  0.10973012,
        0.96299236,  0.9339493 ,  0.83420766,  0.45089015,  0.16814067])

In [8]:
norm.logcdf(r)

array([-2.90991256, -0.03174631, -0.32908009, -2.85738881, -2.20973134,
       -0.0377098 , -0.06833312, -0.18127291, -0.79653153, -1.78295435])