In [2]:
import numpy as np
M = np.array([[1,2],[3,4]])
L = [[1,2],[3,4]]

L[0]

[1, 2]

In [3]:
L[0][0]

1

In [4]:
M[0][0]

1

In [5]:
M[0,0]

1

In [7]:
# official docs say to use np array
M2 = np.matrix([[1,2],[3,4]])
M2

matrix([[1, 2],
        [3, 4]])

In [8]:
A = np.array(M2)
A

array([[1, 2],
       [3, 4]])

In [10]:
# transpose
A.T

array([[1, 3],
       [2, 4]])