In [1]:
import numpy as np

Z = np.zeros(10)
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [2]:
Z = np.zeros((10,10))
Z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [3]:
O = np.ones((10,10))
O

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [5]:
R = np.random.random((10,10))
R

array([[ 0.22125391,  0.52239328,  0.55061302,  0.55515779,  0.29822968,
         0.39987236,  0.60912167,  0.07275901,  0.68461161,  0.60547162],
       [ 0.66903063,  0.51137918,  0.01643419,  0.90210257,  0.03369651,
         0.9653251 ,  0.87907713,  0.08700177,  0.70585852,  0.53393485],
       [ 0.20568399,  0.11271427,  0.75715406,  0.53556279,  0.17582196,
         0.44440719,  0.73091434,  0.90605811,  0.20485908,  0.89798438],
       [ 0.55937901,  0.72707749,  0.96925197,  0.15695167,  0.10101025,
         0.88246491,  0.1651287 ,  0.7826357 ,  0.33798363,  0.22737737],
       [ 0.69066908,  0.06474479,  0.21644915,  0.4081099 ,  0.24171604,
         0.00569328,  0.87296232,  0.55224411,  0.27049883,  0.01445653],
       [ 0.11978204,  0.84416171,  0.82193826,  0.38248843,  0.51805494,
         0.39940433,  0.10059203,  0.19839595,  0.65595839,  0.55212939],
       [ 0.12566404,  0.71586157,  0.16875609,  0.23878584,  0.11300233,
         0.08777702,  0.19439509,  0.31166701

In [6]:
# numbers from gaussian distribution with mean=0, variance=1
G = np.random.randn(10,10)
G

array([[-0.13750368, -0.96465843, -2.36662566,  1.02519152, -0.09389916,
         0.33738365,  0.6789456 , -2.30601168,  0.94152891,  0.901831  ],
       [ 0.76762452, -0.14719766, -0.61564051,  0.12808526,  0.03830038,
        -1.98447806, -1.1200124 , -0.15307316,  0.10725906,  0.31378044],
       [-0.6453334 , -0.34211393,  1.29933267,  0.00545126,  0.48620885,
        -0.64702916,  0.21915005,  0.1526014 ,  0.86531601, -0.27374601],
       [-1.50967075,  0.8981103 , -1.37845483,  0.6186696 ,  0.6749898 ,
        -0.85921816, -1.21809624, -0.18054077,  1.69714465,  0.89520455],
       [-2.02703001,  0.41321775,  0.18892611,  1.04010518,  1.64017825,
         1.36147235,  0.95732787,  0.07289798, -1.2855884 , -1.96268228],
       [ 1.30542481,  0.23675526,  0.13070427,  0.12642346, -1.00742013,
         0.76092586, -0.54994035,  0.95359308, -0.82386178, -0.93859921],
       [ 2.21358038, -2.06442533, -0.42053824,  0.23986474,  1.42971702,
         1.674387  ,  0.47718354, -0.46551552

In [7]:
G.mean()

0.025912157338610159

In [8]:
G.var()

1.0675892372063074