In [2]:
import numpy as np

A = np.array([[1,2],[3,4]])

# inverse
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [3]:
Ainv.dot(A)

array([[  1.00000000e+00,   4.44089210e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [4]:
A.dot(Ainv)

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [5]:
# determinate
np.linalg.det(A)

-2.0000000000000004

In [6]:
# diagonal
np.diag(A)

array([1, 4])

In [7]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [8]:
a = np.array([1,2])
b = np.array([3,4])

# outer product
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [9]:
# inner product
np.inner(a,b)

11

In [10]:
a.dot(b)

11

In [11]:
np.diag(A).sum()

5

In [12]:
np.trace(A)

5

In [15]:
# 100 samples and 3 features
x = np.random.randn(100,3)

# covariance - should be 3x3
cov = np.cov(x)
cov.shape

(100, 100)

In [16]:
# wrong, transpose it first
cov = np.cov(x.T)
cov.shape

(3, 3)

In [18]:
# eigenvalues & eigenvectors
# np.linalg.eig(C) or np.linalg.eigh(C)
# eigh is for symmetric and Hermitian matrices
# symmetric means A = A^T
# Hermitian means A = A^H
# A^H = conjugate transpose of A

np.linalg.eigh(cov)

(array([ 0.79485494,  1.15287417,  1.20893069]),
 array([[-0.52097364,  0.60540345, -0.60172513],
        [ 0.00888139,  0.70875536,  0.70539844],
        [ 0.85352656,  0.36214984, -0.37461969]]))

In [19]:
# first tuple contains three eigenvalues
# second tuple contains eigenvectors stored in columns

np.linalg.eig(cov)

(array([ 0.79485494,  1.20893069,  1.15287417]),
 array([[ 0.52097364,  0.60172513,  0.60540345],
        [-0.00888139, -0.70539844,  0.70875536],
        [-0.85352656,  0.37461969,  0.36214984]]))