In [5]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([1,2])

a

array([[1, 2],
       [3, 4]])

In [6]:
b

array([1, 2])

In [7]:
x = np.linalg.inv(a).dot(b)
x

array([  2.22044605e-16,   5.00000000e-01])

In [8]:
x = np.linalg.solve(a,b)
x

array([ 0. ,  0.5])

In [ ]:
# never use inverse method just use solve like in MATLAB